# Generated by Django 4.1.4 on 2022-12-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_judul_blog_nama_universitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='nama_universitas',
            new_name='title',
        ),
    ]
