# Generated by Django 4.1.4 on 2022-12-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='provinsi',
        ),
    ]
