# Generated by Django 4.1.4 on 2022-12-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_body_blog_kota_rename_category_blog_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kota',
            field=models.CharField(max_length=50),
        ),
    ]
