# Generated by Django 4.1.4 on 2022-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_kota'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
