# Generated by Django 4.1.4 on 2022-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blog_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
